/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as InternsRouteImport } from './routes/interns'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as OpeningHoursRouteImport } from './routes/opening-hours'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as RostersIndexRouteImport } from './routes/rosters.index'
import { Route as RostersHallOfFameRouteImport } from './routes/rosters.hall-of-fame'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const InternsRoute = InternsRouteImport.update({
  id: '/interns',
  path: '/interns',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningHoursRoute = OpeningHoursRouteImport.update({
  id: '/opening-hours',
  path: '/opening-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RostersIndexRoute = RostersIndexRouteImport.update({
  id: '/rosters/',
  path: '/rosters/',
  getParentRoute: () => rootRouteImport,
} as any)
const RostersHallOfFameRoute = RostersHallOfFameRouteImport.update({
  id: '/rosters/hall-of-fame',
  path: '/rosters/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/teams/$slug',
  path: '/teams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/interns': typeof InternsRoute
  '/live': typeof LiveRoute
  '/membership': typeof MembershipRoute
  '/opening-hours': typeof OpeningHoursRoute
  '/our-team': typeof OurTeamRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/$slug': typeof NewsSlugRoute
  '/research/$id': typeof ResearchIdRoute
  '/rosters/hall-of-fame': typeof RostersHallOfFameRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/research/': typeof ResearchIndexRoute
  '/rosters/': typeof RostersIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/interns': typeof InternsRoute
  '/live': typeof LiveRoute
  '/membership': typeof MembershipRoute
  '/opening-hours': typeof OpeningHoursRoute
  '/our-team': typeof OurTeamRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/$slug': typeof NewsSlugRoute
  '/research/$id': typeof ResearchIdRoute
  '/rosters/hall-of-fame': typeof RostersHallOfFameRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/research': typeof ResearchIndexRoute
  '/rosters': typeof RostersIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/interns': typeof InternsRoute
  '/live': typeof LiveRoute
  '/membership': typeof MembershipRoute
  '/opening-hours': typeof OpeningHoursRoute
  '/our-team': typeof OurTeamRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/news/$slug': typeof NewsSlugRoute
  '/research/$id': typeof ResearchIdRoute
  '/rosters/hall-of-fame': typeof RostersHallOfFameRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/research/': typeof ResearchIndexRoute
  '/rosters/': typeof RostersIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/hall-of-fame'
    | '/interns'
    | '/live'
    | '/membership'
    | '/opening-hours'
    | '/our-team'
    | '/privacy'
    | '/shop'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/checkout/return'
    | '/news/$slug'
    | '/research/$id'
    | '/rosters/hall-of-fame'
    | '/teams/$slug'
    | '/research/'
    | '/rosters/'
    | '/teams/'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/hall-of-fame'
    | '/interns'
    | '/live'
    | '/membership'
    | '/opening-hours'
    | '/our-team'
    | '/privacy'
    | '/shop'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/checkout/return'
    | '/news/$slug'
    | '/research/$id'
    | '/rosters/hall-of-fame'
    | '/teams/$slug'
    | '/research'
    | '/rosters'
    | '/teams'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/hall-of-fame'
    | '/interns'
    | '/live'
    | '/membership'
    | '/opening-hours'
    | '/our-team'
    | '/privacy'
    | '/shop'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/checkout/return'
    | '/news/$slug'
    | '/research/$id'
    | '/rosters/hall-of-fame'
    | '/teams/$slug'
    | '/research/'
    | '/rosters/'
    | '/teams/'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HallOfFameRoute: typeof HallOfFameRoute
  InternsRoute: typeof InternsRoute
  LiveRoute: typeof LiveRoute
  MembershipRoute: typeof MembershipRoute
  OpeningHoursRoute: typeof OpeningHoursRoute
  OurTeamRoute: typeof OurTeamRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ResearchIdRoute: typeof ResearchIdRoute
  RostersHallOfFameRoute: typeof RostersHallOfFameRoute
  TeamsSlugRoute: typeof TeamsSlugRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  RostersIndexRoute: typeof RostersIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interns': {
      id: '/interns'
      path: '/interns'
      fullPath: '/interns'
      preLoaderRoute: typeof InternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opening-hours': {
      id: '/opening-hours'
      path: '/opening-hours'
      fullPath: '/opening-hours'
      preLoaderRoute: typeof OpeningHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosters/': {
      id: '/rosters/'
      path: '/rosters'
      fullPath: '/rosters/'
      preLoaderRoute: typeof RostersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosters/hall-of-fame': {
      id: '/rosters/hall-of-fame'
      path: '/rosters/hall-of-fame'
      fullPath: '/rosters/hall-of-fame'
      preLoaderRoute: typeof RostersHallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/teams/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HallOfFameRoute: HallOfFameRoute,
  InternsRoute: InternsRoute,
  LiveRoute: LiveRoute,
  MembershipRoute: MembershipRoute,
  OpeningHoursRoute: OpeningHoursRoute,
  OurTeamRoute: OurTeamRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  NewsSlugRoute: NewsSlugRoute,
  ResearchIdRoute: ResearchIdRoute,
  RostersHallOfFameRoute: RostersHallOfFameRoute,
  TeamsSlugRoute: TeamsSlugRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  RostersIndexRoute: RostersIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
